# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/impl/calc_project/calc_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/impl/calc_project/calc_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/alu.vhd
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/io_ctrl.vhd
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/calc_ctrl.vhd
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/alu_rtl.vhd
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/io_ctrl_rtl.vhd
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/calc_top.vhd
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/calc_ctrl_rtl.vhd
  C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/vhdl/calc_top_rtl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/impl/calc_project/calc_project.srcs/constrs_1/new/calc_constrs.xdc
set_property used_in_implementation false [get_files C:/Users/Michael/Desktop/Elektronik/Sommersemester_2022/CHIP/calculator/impl/calc_project/calc_project.srcs/constrs_1/new/calc_constrs.xdc]


synth_design -top calc_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef calc_top.dcp

catch { report_utilization -file calc_top_utilization_synth.rpt -pb calc_top_utilization_synth.pb }
